### ISSUE TITLE
Make conda installation as well

### ISSUE THREAD

**Issue by iamtekson** [yu9824/kennard_stone#5]
First of all, thank you for writing this library. It is very helpful. But please make it available on conda as well. If you need my help to publish it in the `conda-forge` channel, I will send a PR.

**Comment by yu9824** [comment]
Thank you for your patience.

You can now install this package via the conda-forge channel.

Links;
- My PR: https://github.com/conda-forge/staged-recipes/pull/18779
- Package link: https://anaconda.org/conda-forge/kennard-stone

Best regards,

**Comment by iamtekson** [comment]
Great! Thanks.
