### ISSUE TITLE
Very slow with large amount of data

### ISSUE THREAD

**Issue by pikakolendo02** [yu9824/kennard_stone#8]
Hello yu9824,
The process of `train_test_split` is quite slow with thousands of data.
With 500 data the split takes only a few seconds, but with 2000 data it takes 7 minutes.
The split process seems to use only 1 CPU core.
I look forward to performance optimizations.

**Comment by yu9824** [comment]
Thank you for your feedback.

I too recognize that this is one of the major problems.
I am considering parallelization by specifying the batch size, but have not been able to achieve it yet.

I would appreciate it if you could wait a little longer.
If you have a better way, please let me know.

Best regards,

**Comment by yu9824** [comment]
In response, we have released version v2.1.0 (#9) , which features performance optimizations such as parallelization and algorithm optimization (e.g., replacing recursive functions with for-loops). I believe these updates have partially addressed the issue you identified.

If you have any additional thoughts or ideas on how I can optimize our software, I would love to hear them.

Kind regards,

**Comment by pikakolendo02** [comment]
Thank you for improvement!
However it takes longer on my 16-core R9-5950X (2038 data, 219 features)

n_jobs=1:
CPU times: user 9min 11s, sys: 12.6 s, total: 9min 23s
Wall time: 9min 24s

n_jobs=16:
CPU times: user 6min 13s, sys: 5min 20s, total: 11min 33s
Wall time: 11min 35s
